### PR TITLE
Client view gig

### PR DESCRIPTION
**Pull request by vulong264**
Doctor can:
1. Set up Clinic to work at (Gig page) => Need to add "add clinic page". Responsible by Vinh
2. Set up Gig info such as: cost, booking fee, working hours
Client can:
1. View Gig
2. Click on desired timeslot to book. (booked slot are shown as not available)
3. Complete checkout and payment process.
Note: Payment API is fake. Random Code generation is fake.

### CODE REVIEW

**Comment by tucq88** [comment]
Damn... I know there should be conflict. I'll have a look, if I can't resolve it - I may need a call with you to correct things right

**Comment by vulong264** [comment]
@tucq88 just minor differences in application.js file. It won't take much of your time.

**Comment by tucq88** [comment]
It's just the beginning bro ...

**Comment by vulong264** [comment]
nah. You are a pro git guy. Let me know if you need to clarify anything on my code @tucq88

**Pull request merged**
