### PR TITLE
Multiple model authenticate with devise

### PR DESCRIPTION
**Pull request by kiendt07**
1. User is the model for authentication and authorization. 
2. User has a polymorphic attributes `owner`, which could be a Doctor/Client/Admin. Access owner of User by `user.owner`
3. All other model like Doctor/Client/Admin is linked to User via `user` attribute. Access the user by `doctor.user`
4. Login works as usual. Sign up is tricky: we have to create 2 model: User and Doctor that link to each other.

### CODE REVIEW

**Comment by vulong264** [comment]
I thought you said that @taduyvinh solved the difficulties with multiple usertype signup already? @kiendt07 ???

**Comment by tucq88** [comment]
# not sure this is a hotfix with 20 commits lol 

Can't merge, got error

```
ActiveRecord::DuplicateMigrationVersionError:

Multiple migrations have the version number 20161108225112.
```

when run migration :(

**Comment by tucq88** [comment]
@kiendt07 
2 migration file for doctors table 
image
Consider to remove one ?

**Comment by tucq88** [comment]
@kiendt07 Damn, your branch is not based on master right, you don't have latest updates on master branch 

To be honest I don't understand why we need that complexity, just simple users, admin, doctor .. why need `owner` stuff ??

**Comment by kiendt07** [comment]
@tucq88 sorry ab the conflict :) 
About the `owner`: cause _doctor/admin/client_ are able to authenticate via User, and they also have _extra attributes_ beside the stuff in User, so the `owner` attribute of User link to the owner of that account.

**Comment by tucq88** [comment]
@kiendt07 Still up ? lol, young man. 
No worries about conflict, I tried to resolve but have no idea about your code. So could you please resolve it yourself ? So I could generate devise views and add some frontend works.

**Pull request merged**
